# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3

# Fabric api
fabric_version=0.135.0+1.21.10

# Mod Properties
mod_version=1.7.0
maven_group=dev.gegy
archives_base_name=player-roles
