# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4

# Fabric api
fabric_version=0.140.2+1.21.11

# Mod Properties
mod_version=1.8.1
maven_group=dev.gegy
archives_base_name=player-roles
